[package]
name = "curvefever"
version = "0.1.0"
edition = "2021"

[dependencies]
curvefever_derive = { path = "curvefever_derive" }
egui = "0.22.0"
eframe = "0.22.0"
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
axum = { version = "0.6.20", features = ["ws"] }
crossbeam = "0.8.2"
