[workspace]
members = [
    "curvefever_game",
    "curvefever_remote",
    "curvefever_derive",
]

[workspace.dependencies]
curvefever_derive = { path = "curvefever_derive" }

egui = "0.22.0"
eframe = "0.22.0"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
axum = { version = "0.6.20", features = ["ws"] }
crossbeam = "0.8.2"
futures-util = "0.3.28"
